# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True, default=datetime.datetime(2016, 10, 8, 3, 12, 24, 694375, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
