# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 14:43
from __future__ import unicode_literals

import booksite.book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20161008_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('author', models.CharField(blank=True, db_index=True, max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, max_length=200, null=True, upload_to=booksite.book.models.front_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='site',
            field=models.CharField(blank=True, db_index=True, default='86696', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='b',
            unique_together=set([('title', 'author')]),
        ),
        migrations.AddField(
            model_name='book',
            name='site_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.B'),
        ),
    ]
