# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170429_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='site',
            field=models.CharField(blank=True, db_index=True, default='86696', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookrank',
            name='site_book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.B'),
        ),
    ]
