# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20170429_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.CharField(db_index=True, max_length=24),
        ),
    ]
