# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20171205_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='page_number',
            field=models.IntegerField(db_index=True),
        ),
    ]
