# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20171205_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='book_number',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='next_number',
            field=models.CharField(db_index=True, default='0', max_length=24),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='page_number',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='prev_number',
            field=models.CharField(db_index=True, default='0', max_length=24),
        ),
    ]
