# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20171205_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookpage',
            unique_together=set([('page_number', 'site')]),
        ),
    ]
