# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20171205_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='next_number',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='prev_number',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
    ]
